# 1. DATABASE CONNECTION (PostgreSQL 18)
spring.datasource.url=jdbc:postgresql://localhost:5432/saas_billing_db
spring.datasource.username=postgres
spring.datasource.password=xxx
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Dev-Specific Hibernate Settings
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. SERVER SETTINGS
server.port=8080
server.error.include-message=always